/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 2
#line 1 "src/parser.leg"

#define YY_CTX_LOCAL

#include <stdio.h>
#include "action.h"

word_node_t* head = NULL;

#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_word(yycontext *yy); /* 2 */
YY_RULE(int) yy_start(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_word(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_word\n"));
  {
#line 97
  
        if (head == NULL) {
            head = create_word_node(yytext);
        } else {
            add_word_node(head, yytext);
        }
    ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_word(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "word"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l1;
#undef yytext
#undef yyleng
  }
  {  int yypos4= yy->__pos, yythunkpos4= yy->__thunkpos;  if (!yymatchString(yy, "Ա")) goto l5;  goto l4;
  l5:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Բ")) goto l6;  goto l4;
  l6:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Գ")) goto l7;  goto l4;
  l7:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Դ")) goto l8;  goto l4;
  l8:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ե")) goto l9;  goto l4;
  l9:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Զ")) goto l10;  goto l4;
  l10:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Է")) goto l11;  goto l4;
  l11:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ը")) goto l12;  goto l4;
  l12:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Թ")) goto l13;  goto l4;
  l13:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ժ")) goto l14;  goto l4;
  l14:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ի")) goto l15;  goto l4;
  l15:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Լ")) goto l16;  goto l4;
  l16:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Խ")) goto l17;  goto l4;
  l17:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ծ")) goto l18;  goto l4;
  l18:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Կ")) goto l19;  goto l4;
  l19:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Հ")) goto l20;  goto l4;
  l20:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ձ")) goto l21;  goto l4;
  l21:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ղ")) goto l22;  goto l4;
  l22:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ճ")) goto l23;  goto l4;
  l23:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Մ")) goto l24;  goto l4;
  l24:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Յ")) goto l25;  goto l4;
  l25:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ն")) goto l26;  goto l4;
  l26:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Շ")) goto l27;  goto l4;
  l27:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ո")) goto l28;  goto l4;
  l28:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Չ")) goto l29;  goto l4;
  l29:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Պ")) goto l30;  goto l4;
  l30:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ջ")) goto l31;  goto l4;
  l31:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ռ")) goto l32;  goto l4;
  l32:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ս")) goto l33;  goto l4;
  l33:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Վ")) goto l34;  goto l4;
  l34:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Տ")) goto l35;  goto l4;
  l35:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ր")) goto l36;  goto l4;
  l36:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ց")) goto l37;  goto l4;
  l37:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ւ")) goto l38;  goto l4;
  l38:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Փ")) goto l39;  goto l4;
  l39:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ք")) goto l40;  goto l4;
  l40:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Օ")) goto l41;  goto l4;
  l41:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ֆ")) goto l42;  goto l4;
  l42:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "Ո")) goto l43;  goto l4;
  l43:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ա")) goto l44;  goto l4;
  l44:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "բ")) goto l45;  goto l4;
  l45:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "գ")) goto l46;  goto l4;
  l46:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "դ")) goto l47;  goto l4;
  l47:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ե")) goto l48;  goto l4;
  l48:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "զ")) goto l49;  goto l4;
  l49:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "է")) goto l50;  goto l4;
  l50:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ը")) goto l51;  goto l4;
  l51:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "թ")) goto l52;  goto l4;
  l52:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ժ")) goto l53;  goto l4;
  l53:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ի")) goto l54;  goto l4;
  l54:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "լ")) goto l55;  goto l4;
  l55:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "խ")) goto l56;  goto l4;
  l56:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ծ")) goto l57;  goto l4;
  l57:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "կ")) goto l58;  goto l4;
  l58:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "հ")) goto l59;  goto l4;
  l59:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ձ")) goto l60;  goto l4;
  l60:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ղ")) goto l61;  goto l4;
  l61:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ճ")) goto l62;  goto l4;
  l62:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "մ")) goto l63;  goto l4;
  l63:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "յ")) goto l64;  goto l4;
  l64:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ն")) goto l65;  goto l4;
  l65:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "շ")) goto l66;  goto l4;
  l66:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ո")) goto l67;  goto l4;
  l67:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "չ")) goto l68;  goto l4;
  l68:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "պ")) goto l69;  goto l4;
  l69:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ջ")) goto l70;  goto l4;
  l70:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ռ")) goto l71;  goto l4;
  l71:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ս")) goto l72;  goto l4;
  l72:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "վ")) goto l73;  goto l4;
  l73:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "տ")) goto l74;  goto l4;
  l74:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ր")) goto l75;  goto l4;
  l75:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ց")) goto l76;  goto l4;
  l76:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ւ")) goto l77;  goto l4;
  l77:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "փ")) goto l78;  goto l4;
  l78:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ք")) goto l79;  goto l4;
  l79:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "օ")) goto l80;  goto l4;
  l80:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ֆ")) goto l81;  goto l4;
  l81:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "ո")) goto l82;  goto l4;
  l82:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "և")) goto l1;
  }
  l4:;	
  l2:;	
  {  int yypos3= yy->__pos, yythunkpos3= yy->__thunkpos;
  {  int yypos83= yy->__pos, yythunkpos83= yy->__thunkpos;  if (!yymatchString(yy, "Ա")) goto l84;  goto l83;
  l84:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Բ")) goto l85;  goto l83;
  l85:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Գ")) goto l86;  goto l83;
  l86:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Դ")) goto l87;  goto l83;
  l87:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ե")) goto l88;  goto l83;
  l88:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Զ")) goto l89;  goto l83;
  l89:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Է")) goto l90;  goto l83;
  l90:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ը")) goto l91;  goto l83;
  l91:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Թ")) goto l92;  goto l83;
  l92:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ժ")) goto l93;  goto l83;
  l93:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ի")) goto l94;  goto l83;
  l94:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Լ")) goto l95;  goto l83;
  l95:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Խ")) goto l96;  goto l83;
  l96:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ծ")) goto l97;  goto l83;
  l97:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Կ")) goto l98;  goto l83;
  l98:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Հ")) goto l99;  goto l83;
  l99:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ձ")) goto l100;  goto l83;
  l100:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ղ")) goto l101;  goto l83;
  l101:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ճ")) goto l102;  goto l83;
  l102:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Մ")) goto l103;  goto l83;
  l103:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Յ")) goto l104;  goto l83;
  l104:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ն")) goto l105;  goto l83;
  l105:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Շ")) goto l106;  goto l83;
  l106:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ո")) goto l107;  goto l83;
  l107:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Չ")) goto l108;  goto l83;
  l108:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Պ")) goto l109;  goto l83;
  l109:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ջ")) goto l110;  goto l83;
  l110:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ռ")) goto l111;  goto l83;
  l111:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ս")) goto l112;  goto l83;
  l112:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Վ")) goto l113;  goto l83;
  l113:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Տ")) goto l114;  goto l83;
  l114:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ր")) goto l115;  goto l83;
  l115:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ց")) goto l116;  goto l83;
  l116:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ւ")) goto l117;  goto l83;
  l117:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Փ")) goto l118;  goto l83;
  l118:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ք")) goto l119;  goto l83;
  l119:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Օ")) goto l120;  goto l83;
  l120:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ֆ")) goto l121;  goto l83;
  l121:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "Ո")) goto l122;  goto l83;
  l122:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ա")) goto l123;  goto l83;
  l123:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "բ")) goto l124;  goto l83;
  l124:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "գ")) goto l125;  goto l83;
  l125:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "դ")) goto l126;  goto l83;
  l126:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ե")) goto l127;  goto l83;
  l127:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "զ")) goto l128;  goto l83;
  l128:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "է")) goto l129;  goto l83;
  l129:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ը")) goto l130;  goto l83;
  l130:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "թ")) goto l131;  goto l83;
  l131:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ժ")) goto l132;  goto l83;
  l132:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ի")) goto l133;  goto l83;
  l133:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "լ")) goto l134;  goto l83;
  l134:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "խ")) goto l135;  goto l83;
  l135:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ծ")) goto l136;  goto l83;
  l136:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "կ")) goto l137;  goto l83;
  l137:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "հ")) goto l138;  goto l83;
  l138:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ձ")) goto l139;  goto l83;
  l139:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ղ")) goto l140;  goto l83;
  l140:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ճ")) goto l141;  goto l83;
  l141:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "մ")) goto l142;  goto l83;
  l142:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "յ")) goto l143;  goto l83;
  l143:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ն")) goto l144;  goto l83;
  l144:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "շ")) goto l145;  goto l83;
  l145:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ո")) goto l146;  goto l83;
  l146:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "չ")) goto l147;  goto l83;
  l147:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "պ")) goto l148;  goto l83;
  l148:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ջ")) goto l149;  goto l83;
  l149:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ռ")) goto l150;  goto l83;
  l150:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ս")) goto l151;  goto l83;
  l151:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "վ")) goto l152;  goto l83;
  l152:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "տ")) goto l153;  goto l83;
  l153:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ր")) goto l154;  goto l83;
  l154:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ց")) goto l155;  goto l83;
  l155:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ւ")) goto l156;  goto l83;
  l156:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "փ")) goto l157;  goto l83;
  l157:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ք")) goto l158;  goto l83;
  l158:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "օ")) goto l159;  goto l83;
  l159:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ֆ")) goto l160;  goto l83;
  l160:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "ո")) goto l161;  goto l83;
  l161:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yymatchString(yy, "և")) goto l3;
  }
  l83:;	  goto l2;
  l3:;	  yy->__pos= yypos3; yy->__thunkpos= yythunkpos3;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l1;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_word, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "word", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "word", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_start(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "start"));
  {  int yypos163= yy->__pos, yythunkpos163= yy->__thunkpos;  if (!yy_word(yy)) goto l164;  goto l163;
  l164:;	  yy->__pos= yypos163; yy->__thunkpos= yythunkpos163;  if (!yymatchDot(yy)) goto l162;
  }
  l163:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 1;
  l162:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_start);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 106 "src/parser.leg"



